name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install tools
      run: make tools

    - name: Build
      run: make

    - name: Package
      run: make package

    # - name : Upload packages (linux-amd64)
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: crash-exporter (linux-amd64)
    #     path: crash_exporter.linux-amd64.tar.gz

    - name: Create a Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          crash_exporter.linux-amd64.tar.gz
          crash_exporter.linux-arm64.tar.gz
